### ISSUE TITLE
Jellyfin not starting with JellyfinTray.exe

### ISSUE THREAD

**Issue by ketanarlulkar** [jellyfin/jellyfin-server-windows#18]
I just installed Jellyfin with basic setup. When clicked on JellyfinTray.exe, Jellyfin won't start.
So clicked on jellyfin.exe, saw following error on the command prompt.
I'm able to access the web UI as long as this command prompt is open.

```
[19:31:46] [INF] Jellyfin version: 10.4.1
[19:31:46] [INF] Arguments: ["C:\\Program Files\\Jellyfin\\Server\\jellyfin.dll"]
[19:31:46] [INF] Operating system: Windows
[19:31:46] [INF] Architecture: X64
[19:31:46] [INF] 64-Bit Process: True
[19:31:46] [INF] User Interactive: True
[19:31:46] [INF] Processor count: 4
[19:31:46] [INF] Program data path: C:\Users\User\AppData\Local\jellyfin
[19:31:46] [INF] Web resources path: C:\Program Files\Jellyfin\Server\jellyfin-web
[19:31:46] [INF] Application directory: C:\Program Files\Jellyfin\Server\
[19:31:46] [INF] Setting cache path to C:\Users\User\AppData\Local\jellyfin\cache
[19:31:46] [INF] Loading assemblies
[19:31:49] [INF] Kestrel listening on all interfaces
[19:31:49] [INF] Running startup tasks
[19:31:49] [INF] Daily trigger for Chapter image extraction set to fire at 11/22/2019 02:00, which is 6:28:10.9085332 from now.
[19:31:49] [INF] Found ffmpeg version unknown
[19:31:49] [WRN] FFmpeg: System: Failed version check: C:\Program Files\Jellyfin\Server\ffmpeg.exe
[19:31:49] [INF] Available decoders: ["h264", "h264_qsv", "h264_cuvid", "hevc", "hevc_qsv", "hevc_cuvid", "mpeg2video", "mpeg2_qsv", "vc1_qsv", "aac", "ac3", "mp3"]
[19:31:49] [INF] Available encoders: ["libx264", "h264_nvenc", "h264_qsv", "libx265", "hevc_nvenc", "hevc_qsv", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "ac3", "libmp3lame", "libopus", "libvorbis", "srt"]
[19:31:49] [INF] FFmpeg: System: C:\Program Files\Jellyfin\Server\ffmpeg.exe
[19:31:49] [INF] ServerId: 3e9fee1d580042e8a9d6ed17ce203d5d
[19:31:49] [INF] Executed all pre-startup entry points in 0:00:00.197022
[19:31:49] [INF] Core startup complete
[19:31:49] [INF] Registering publisher for urn:schemas-upnp-org:device:MediaServer:1 on 192.168.0.123
[19:31:50] [INF] Executed all post-startup entry points in 0:00:00.3273968
[19:31:52] [INF] StartupTrigger fired for task: Check for plugin updates
[19:31:52] [INF] Queueing task PluginUpdateTask
[19:31:52] [INF] Executing Check for plugin updates
[19:31:52] [INF] Check for plugin updates Completed after 0 minute(s) and 0 seconds
[19:31:52] [INF] ExecuteQueuedTasks
[19:31:52] [INF] WS http://localhost:8096/socket?api_key=c15a98165b4b47fbafdcf50f99029916&deviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzc2LjAuMzgwOS4xMzIgU2FmYXJpLzUzNy4zNnwxNTY4MjA5NDU1NTgx. UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
[19:31:58] [ERR] Error creating http port map
MediaBrowser.Model.Net.HttpException: Internal Server Error
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.EnsureSuccessStatusCode(HttpResponseMessage response, HttpRequestOptions options)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
   at Mono.Nat.Upnp.UpnpNatDevice.CreatePortMap(Mapping mapping)
   at Emby.Server.Implementations.EntryPoints.ExternalPortForwarding.CreateRules(INatDevice device)
```

**Comment by joaovitoriasilva** [comment]
Hi there,

Also have this issue. Glad to see that what is doing this is identified. Do you know (more or less) when will be patched? Only thing blocking me from killing plex :)

**Comment by pusta** [comment]
I also had this issue this morning after the latest round of .net updates.  The error in the event log is:

Description: A .NET Core application failed.
Application: JellyfinTray.exe
Path: C:\Program Files\Jellyfin\Server\JellyfinTray.exe
Message: The application to execute does not exist: 'C:\Users\Chris\AppData\Local\Temp\.net\JellyfinTray\l2cxugcr.jn2\JellyfinTray.dll'.

If I delete the %temp%\.net\Jellyfin folder and restart the app, it works.

**Comment by LennyLip** [comment]
> ReadOnly: SQLitePCL.pretty.SQLiteException: attempt to write a readonly database

same issue with installer/jellyfin_10.7.6_windows-x64.exe
